# Generated by Django 4.1.2 on 2022-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('value', models.FloatField(default=0)),
                ('isSecret', models.BooleanField(default=False)),
            ],
        ),
    ]
